//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InzService
{
    using System;
    using System.Collections.Generic;
    
    public partial class TemperatureTable
    { 
        public long Id { get; set; }
        public string Temperature { get; set; }
        public string Address { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<byte> FanStatus { get; set; }
    }
}
